### ISSUE TITLE
idea无法启动项目

### ISSUE THREAD

**Issue by caizhixiang** [aaronwong1989/blind-watermark#2]
既然是springboot项目，为啥不能由idea那里main方法直接启动？一启动就报 “no jniopencv_core in java.library.path”，需要在“java.library.path”放入.dll.
为啥直接通过“java -jar xxx.jar”的方式又可以访问？
这两种启动方式有什么不同吗？

**Comment by aaronwong1989** [comment]
估计使用的JDK不同，或者环境变量不同。

**Comment by aaronwong1989** [comment]
估计使用的JDK不同，或者环境变量不同。
