### ISSUE TITLE
请问可以提取经过打印后扫描或者手机拍摄的图的水印吗

### ISSUE THREAD

**Issue by xgyyao** [aaronwong1989/blind-watermark#4]

**Comment by aaronwong1989** [comment]
应该不可以，你这种需求适合明水印。发自我的华为手机-------- 原始邮件 --------发件人： xgyyao <notifications@github.com>日期： 2019年9月6日周五 16:06收件人： aaronwong1989/blind-watermark <blind-watermark@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [aaronwong1989/blind-watermark] 请问可以提取经过打印后扫描或者手机拍摄的图的水印吗 (#4)

**Comment by aaronwong1989** [comment]
需求不适用于盲水印，盲水印适应于数字防伪，不适用于图像视觉上相关的需求
